spring.application.name=horizon

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/horizondb
spring.datasource.username=barcvilla
spring.datasource.password=b4000$.
spring.datasource.driver-class-name=org.postgresql.Driver