spring.application.name=horizon

#create	Crea tablas al iniciar (si existen, no hace nada)
#create-drop	Crea al iniciar, elimina al cerrar la sesión
#update	Solo agrega columnas que faltan (más seguro para prod)
#none	No toca el schema

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/horizondb
spring.datasource.username=barcvilla
spring.datasource.password=b4000$.
spring.datasource.driver-class-name=org.postgresql.Driver

#jdbc.driverClassName=org.postgresql.Driver
#jdbc.url=jdbc:postgresql://localhost:5432/horizondb
#jdbc.username=barcvilla
#jdbc.password=b4000$.